### ISSUE TITLE
[Feature] Add option to generate multiple stories

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/storybook-genie#17]
**Description**
Currently, the tool allows the users to select one file that can generate a story from.

**Describe the solution you'd like**
The user should be able to select if it want to create a single story or multiple. The user should specify the location of the components that wants to generate stories for. The CLI should then generate stories for all the matching files and save them in the same directory as the source files. The CLI should also display a message indicating how many stories were generated and where they were saved.

**Comment by Ananta2003** [comment]
I would love to work on this issue can you assign me ?
