### ISSUE TITLE
[Feature] Add option to connect to ollama

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/storybook-genie#29]
**Description**
A free alternative to generate the stories would be useful. Right now the cli uses only the OpenAI SDK.

**Describe the solution you'd like**
The cli tool should ask the user which method to use, OpenAI or Ollama. If Ollama is selected the connection details should be added by the user, if OpenAI is selected only the Api key should be added.
Another option would be to just add the connection details in the .env file and automatically select the ollama option.

**Comment by sahoobiks** [comment]
I have looked into the issue about integrating Ollama as a free alternative to the OpenAI SDK, and I would like to work on it.
My Approach:
1. I will implement a simple dropdown in the UI for users to choose between OpenAI and Ollama.
2. The API request will be modified to send the selected model to the backend.
3. I will adjust the endpoint to handle both models without affecting existing functionality. A new function for Ollama will be created to manage its API calls.
This approach ensures we maintain the current app logic while providing users with more options.
Could you please assign this issue to me?

**Comment by eduardconstantin** [comment]
Sounds great!

**Comment by Bisha18** [comment]
Interested could, I work upon it.

**Comment by eduardconstantin** [comment]
> Interested could, I work upon it.

let's give @sahoobiks a chance first

**Comment by eduardconstantin** [comment]
@sahoobiks are you still working on this feature? 
I saw you closed the pr

**Comment by eduardconstantin** [comment]
@Bisha18 I think you can take it

**Comment by eduardconstantin** [comment]
Sounds great! I assigned you.

**Comment by aaryak1369** [comment]
@eduardconstantin do you have your own ollama public key?

**Comment by eduardconstantin** [comment]
> @eduardconstantin do you have your own ollama public key?

you don't need an api key, you have to install ollama locally to use it

**Comment by eduardconstantin** [comment]
@aaryak1369 are you still working on this issue?
