### ISSUE TITLE
[Feature] Inquirer file path alternative

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/storybook-genie#3]
Currently the cli uses Inquirer file path to show the user a file selection input in the terminal. This package uses lodash 3.10.1 which has a security warning.
I am looking for an alternative file path selector in order to remove this warning.

**Comment by datsfilipe** [comment]
[cli-file-select](https://github.com/mykeels/cli-file-select) looks a good option and it doesn't have a lot of dependencies too.

**Comment by eduardconstantin** [comment]
@datsfilipe I check that one, I see it uses this package [prompts](https://github.com/terkelg/prompts) 
I also found [this](https://github.com/SBoudrias/Inquirer.js/tree/master/packages/core) from inquirer, maybe I can do something with it
