### ISSUE TITLE
[BUG] Exit icon

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/storybook-genie#31]
The exit icon seems to have been squashed and it needs to be replaced.
It was supposed to be this one: ⓧ
![image](https://github.com/user-attachments/assets/790303d0-5f1e-475a-8f14-2534cdecd676)

**Comment by Lokeshsuwalka05** [comment]
Can you Assign this issue to me??

**Comment by Lokeshsuwalka05** [comment]
Can we add X instead of ⓧ??

**Comment by eduardconstantin** [comment]
@Lokeshsuwalka05 any progress?

**Comment by Lokeshsuwalka05** [comment]
Can I use ❌ and ✘ instead of ⓧ?

**Comment by Lokeshsuwalka05** [comment]
I think the ⓧ is squashed because of the terminal font settings. When I change the terminal letter spacing, it works well, like terminal.integrated.letterSpacing: 2.

**Comment by Lokeshsuwalka05** [comment]
https://github.com/user-attachments/assets/0304e4d3-6158-494b-8fef-a75837f9f331

**Comment by eduardconstantin** [comment]
@Lokeshsuwalka05 I think they change that in a recent update.
Try to change the icon to this ❌

**Comment by Lokeshsuwalka05** [comment]
I have Resolved the problem you can check
